LOAD DATA LOCAL INFILE 'C:/Users/P7120483/Downloads/TBX_final/data/small/bank.csv'
INTO TABLE bank
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/P7120483/Downloads/TBX_final/data/small/account.csv'
INTO TABLE account
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:/Users/P7120483/Downloads/TBX_final/data/small/transaction.csv'
INTO TABLE transaction
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
